### ISSUE TITLE
Disable sensor jitter by default on 2835

### ISSUE THREAD

**Issue by davidhoness** [RPi-Distro/python-sense-emu#1]
Can we disable sensor emulation in the preferences by default on all 2835 based Raspberry Pi models to save CPU performance for the users Python script?

**Comment by waveform80** [comment]
They can, but there's a semi-conflict here with #4. When the application starts up for the very first time no preferences will have been set, and I can detect that in the app and set the initial values of the simulation settings according to whether or not we're running on a 2835 or not.

However, once the user fires up the preferences window and clicks "OK", they'll have explicitly set the preferences for the simulation running or not (even if they haven't actually clicked those check boxes, nonetheless the settings will be "written"). Now, at that point for the simulation check boxes, do I use the settings stored in the GSettings database for the initial value or do I base the initial value on the processor type?

I'd suggest use the stored settings because that way at least all the controls are consistent with each other: they'll all be restored on startup but the very first run will use settings based on processor type.

**Comment by davidhoness** [comment]
Yes I agree, default to disabled sensor emulation on 2835 only if the preferences have not been set by the user.
