### ISSUE TITLE
Increase Compatibility (windows, etc)

### ISSUE THREAD

**Issue by bsimmo** [RPi-Distro/python-sense-emu#21]
Hello, I use the emu a lot on the Pi where it works very well.
Now Thonny is the IDE of choice, using Thonny on Windows10 is also easy to use and mirrors the setup.

Unfortunately it's not going to work on there, sense_emu does, but the emulator itself doesn't.
I remember this being around the use of PyGObject/GTK3 and Thonny cannot find anything compatible.
I don't believe the mentioned methods in the release blog comments
https://www.raspberrypi.org/blog/desktop-sense-hat-emulator/#comment-1263310 
would not work as Thonny uses Python 3.6 (I know it's 3.4* in Thonny Pi).
I know there is Trinket but it lacks the debug feature etc of Thonny.

I don't know if anything is feasible or you have anything in the pipeline.

- Ideas
-Move to a universally capable HTML5 emulation object (you have the basis from Trinket ?)
-tkinter (as per guizero ?)

Sorry, no real idea but just thought I would ask.

**Comment by waveform80** [comment]
I'm afraid moving to an HTML5 basis is more or less out of the question - the desktop emulator shares no basis with the trinket emulator (for good reason as they're running on entirely different languages and runtimes), and I'm not sure Tk is really up to making an interface like the emulator's. Personally, I think Qt would be a better direction to go in as Windows support is considerably better there (and it's generally a lot less flaky than Gtk3 in my experience). However, it would again be a considerable amount of work to port the current emulator over to Qt (not as much as HTML5 though).

Given the effort involved I suspect the only realistic solution at the moment is to hope that Gtk3 support improves on Windows (the emulator *can* run on Windows; it's just a royal pain to get it set up and working). I'd hoped in the years since I last tried it, Gtk would at least have an official package or installer ... apparently [they have](https://www.gtk.org/download/windows.php) but it's basically "install a command line and learn how to drive a package manager from there". In other words, Windows support in Gtk is still very much "oh, do we really have to?".
